POST http://localhost:8080/api/phone-book/item
content-type: application/json

{
  "name" : "Jan",
  "family_name" : "Kowalski",
  "phone": "+48123456789"
}

###
GET http://localhost:8080/api/phone-book/item/2
accept: application/json
if-none-match: *

###
PUT http://localhost:8080/api/phone-book/item/2
content-type: application/json
if-match: 2

{
  "name" : "Sobieslaw",
  "family_name" : "Nowak",
  "phone": "+48123456789"
}

